'use client';
import { useEffect, useState } from 'react';
const types=['ARTICLE','LESSON','STORY','BOOK','ANIMATION','MARTYR','DAILY','MADAHI','MADAHI_TEXT','DUA','ZIYARAT','QURAN','FIQH','NAHJ','SAHIFA','EVENT','ACTIVITY'];
const labels:any={ARTICLE:'مقاله',LESSON:'درسنامه',STORY:'داستان',BOOK:'کتاب',ANIMATION:'انیمیشن',DAILY:'روزانه',MADAHI:'مداحی',MADAHI_TEXT:'متن مداحی',DUA:'دعا',ZIYARAT:'زیارت',QURAN:'قرآن',FIQH:'احکام',NAHJ:'نهج‌البلاغه',SAHIFA:'صحیفه',EVENT:'مناسبت',ACTIVITY:'فعالیت',MARTYR:'شهدا'};
export default function ContentAdmin(){const [items,setItems]=useState<any[]>([]); const [editing,setEditing]=useState<any>(null); const [msg,setMsg]=useState('');
async function load(){const r=await fetch('/api/admin/content');if(r.ok)setItems(await r.json())} useEffect(()=>{load()},[]);
function blank(){return {title:'',slug:'',type:'ARTICLE',excerpt:'',body:'',status:'DRAFT',sourceUrl:'',license:''}}
async function save(e:any){e.preventDefault();const method=editing.id?'PATCH':'POST';const r=await fetch('/api/admin/content',{method,headers:{'content-type':'application/json'},body:JSON.stringify(editing)});if(r.ok){setMsg('ذخیره شد.');setEditing(null);load()}else{const j=await r.json();setMsg(j.error||'خطا')}}
async function del(id:string){if(!confirm('این محتوا حذف شود؟'))return;await fetch('/api/admin/content',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});load()}
return <section className="adminPage"><div className="container"><div className="adminHeader"><div><span className="sectionKicker">محتوا</span><h1>مدیریت محتوای سایت</h1></div><button className="btn btnDark" onClick={()=>setEditing(blank())}>+ محتوای جدید</button></div>{msg&&<div className="successBox">{msg}</div>}{editing&&<form onSubmit={save} className="editorCard"><h2>{editing.id?'ویرایش محتوا':'محتوای جدید'}</h2><div className="formGrid"><input required placeholder="عنوان" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/><input required placeholder="slug انگلیسی" value={editing.slug} onChange={e=>setEditing({...editing,slug:e.target.value})}/><select value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value})}>{types.map(t=><option key={t} value={t}>{labels[t]}</option>)}</select><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="DRAFT">پیش‌نویس</option><option value="PUBLISHED">منتشر شده</option><option value="ARCHIVED">آرشیو</option></select><input placeholder="منبع / URL" value={editing.sourceUrl||''} onChange={e=>setEditing({...editing,sourceUrl:e.target.value})}/><input placeholder="مجوز انتشار" value={editing.license||''} onChange={e=>setEditing({...editing,license:e.target.value})}/><textarea placeholder="خلاصه" value={editing.excerpt||''} onChange={e=>setEditing({...editing,excerpt:e.target.value})}/><textarea className="wide" placeholder="متن محتوا" value={editing.body||''} onChange={e=>setEditing({...editing,body:e.target.value})}/></div><div className="formActions"><button className="btn btnDark">ذخیره</button><button type="button" className="btn btnGhost" onClick={()=>setEditing(null)}>انصراف</button></div></form>}
<div className="tableCard"><table><thead><tr><th>عنوان</th><th>نوع</th><th>وضعیت</th><th>منبع</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.title}</td><td>{labels[x.type]||x.type}</td><td>{x.status}</td><td>{x.sourceUrl?'دارد':'—'}</td><td><button onClick={()=>setEditing(x)}>ویرایش</button><button className="danger" onClick={()=>del(x.id)}>حذف</button></td></tr>)}</tbody></table></div></div></section>}
