CREATE TYPE "ContentStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
CREATE TYPE "ContentType" AS ENUM ('ARTICLE','LESSON','STORY','BOOK','ANIMATION','MARTYR','DAILY','MADAHI','MADAHI_TEXT','DUA','ZIYARAT','QURAN','FIQH','NAHJ','SAHIFA','EVENT','ACTIVITY');
CREATE TYPE "SourceKind" AS ENUM ('OFFICIAL','PUBLIC_DOMAIN','OPEN_LICENSE','USER_SUBMITTED','MANUAL');
CREATE TYPE "FaqMarja" AS ENUM ('KHAMENEI','SISTANI','MAKAREM');
CREATE TYPE "TextWork" AS ENUM ('NAHJ_AL_BALAGHA','SAHIFA_SAJJADIYA');
CREATE TABLE "Source"("id" TEXT NOT NULL,"name" TEXT NOT NULL,"url" TEXT NOT NULL,"kind" "SourceKind" NOT NULL,"license" TEXT,"allowed" BOOLEAN NOT NULL DEFAULT false,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Source_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "Source_url_key" ON "Source"("url");
CREATE TABLE "Tag"("id" TEXT NOT NULL,"name" TEXT NOT NULL,CONSTRAINT "Tag_pkey" PRIMARY KEY("id")); CREATE UNIQUE INDEX "Tag_name_key" ON "Tag"("name");
CREATE TABLE "Content"("id" TEXT NOT NULL,"type" "ContentType" NOT NULL,"title" TEXT NOT NULL,"slug" TEXT NOT NULL,"excerpt" TEXT,"body" TEXT,"mediaUrl" TEXT,"coverImage" TEXT,"status" "ContentStatus" NOT NULL DEFAULT 'DRAFT',"sourceId" TEXT,"sourceUrl" TEXT,"license" TEXT,"publishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Content_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "Content_slug_key" ON "Content"("slug");
CREATE TABLE "ContentTag"("contentId" TEXT NOT NULL,"tagId" TEXT NOT NULL,CONSTRAINT "ContentTag_pkey" PRIMARY KEY("contentId","tagId"));
CREATE TABLE "Martyr"("id" TEXT NOT NULL,"name" TEXT NOT NULL,"birthDate" TEXT,"martyrDate" TEXT,"city" TEXT,"biography" TEXT,"quote" TEXT,"imageUrl" TEXT,"sourceUrl" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Martyr_pkey" PRIMARY KEY("id"));
CREATE TABLE "Prayer"("id" TEXT NOT NULL,"title" TEXT NOT NULL,"category" TEXT NOT NULL,"arabic" TEXT NOT NULL,"translation" TEXT,"source" TEXT,"audioUrl" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Prayer_pkey" PRIMARY KEY("id"));
CREATE TABLE "QuranAyah"("id" TEXT NOT NULL,"surahNo" INTEGER NOT NULL,"surahName" TEXT NOT NULL,"ayahNo" INTEGER NOT NULL,"arabic" TEXT NOT NULL,"translation" TEXT,"audioUrl" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "QuranAyah_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "QuranAyah_surahNo_ayahNo_key" ON "QuranAyah"("surahNo","ayahNo");
CREATE TABLE "FiqhAnswer"("id" TEXT NOT NULL,"marja" "FaqMarja" NOT NULL,"question" TEXT NOT NULL,"answer" TEXT NOT NULL,"sourceUrl" TEXT NOT NULL,"sourceTitle" TEXT,"category" TEXT,"keywords" TEXT,"issueNumber" TEXT,"sourceName" TEXT,"verifiedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "FiqhAnswer_pkey" PRIMARY KEY("id"));
CREATE TABLE "CalendarEvent"("id" TEXT NOT NULL,"date" TIMESTAMP(3) NOT NULL,"jalaliDate" TEXT,"hijriDate" TEXT,"title" TEXT NOT NULL,"category" TEXT NOT NULL,"isHoliday" BOOLEAN NOT NULL DEFAULT false,"description" TEXT,"sourceUrl" TEXT,CONSTRAINT "CalendarEvent_pkey" PRIMARY KEY("id"));
CREATE TABLE "PrayerTime"("id" TEXT NOT NULL,"city" TEXT NOT NULL,"country" TEXT NOT NULL,"date" TIMESTAMP(3) NOT NULL,"fajr" TEXT NOT NULL,"sunrise" TEXT NOT NULL,"dhuhr" TEXT NOT NULL,"asr" TEXT NOT NULL,"maghrib" TEXT NOT NULL,"isha" TEXT NOT NULL,"midnight" TEXT,"method" TEXT,CONSTRAINT "PrayerTime_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "PrayerTime_city_country_date_key" ON "PrayerTime"("city","country","date");
CREATE TABLE "Activity"("id" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"imageUrl" TEXT,"date" TIMESTAMP(3),"location" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Activity_pkey" PRIMARY KEY("id"));
CREATE TABLE "Settings"("key" TEXT NOT NULL,"value" TEXT NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Settings_pkey" PRIMARY KEY("key"));
CREATE TABLE "IslamicText"("id" TEXT NOT NULL,"work" "TextWork" NOT NULL,"section" TEXT,"title" TEXT NOT NULL,"arabic" TEXT,"translation" TEXT,"explanation" TEXT,"source" TEXT,"sourceUrl" TEXT,"audioUrl" TEXT,"number" INTEGER,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "IslamicText_pkey" PRIMARY KEY("id"));
CREATE INDEX "IslamicText_work_number_idx" ON "IslamicText"("work","number");
ALTER TABLE "Content" ADD CONSTRAINT "Content_sourceId_fkey" FOREIGN KEY("sourceId") REFERENCES "Source"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ContentTag" ADD CONSTRAINT "ContentTag_contentId_fkey" FOREIGN KEY("contentId") REFERENCES "Content"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ContentTag" ADD CONSTRAINT "ContentTag_tagId_fkey" FOREIGN KEY("tagId") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;
